### ISSUE TITLE
Allow setting of telemetry state on a stream

### ISSUE THREAD

**Issue by mjclarke94** [RobSpectre/mvf1#1]
Pressing "T" on a stream cycles between no overlay, driver TLA/picture, and a telemetry overlay. It would be great to be able to do this via this library

**Comment by RobSpectre** [comment]
Thanks for the ticket!

There is not currently a way to do this with the MultiViewer API, so I opened a feature request ticket on your behalf.

If you would like to weigh in, you can find it here: https://github.com/f1multiviewer/issue-tracker/issues/389.

Thanks again - will keep you updated if this happens.

**Comment by mjclarke94** [comment]
Hi Rob,

Was playing around with the graphql interface recently, and the mutation now exists in as `playerSetDriverHeaderMode`.

**Comment by RobSpectre** [comment]
@mjclarke94 Thank you for the heads up on this feature! Hope you have a great season.

Just cut [1.1.2](https://github.com/RobSpectre/mvf1/tree/1.1.2) with this added. Closing.

**Comment by mjclarke94** [comment]
Awesome, thanks very much! 

Nothing like a bit of python to distract from the inevitable Verstappen sweep.
